name: Build

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: Android SO
            runs-on: ubuntu-latest
            artifact_name: libMod
            artifact_path: build/libMod.so # CMakeLists.txt에서 정한 이름에 맞춰 확인

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # 만약 나중에 서브모듈로 바꿀 경우를 대비

      - name: Set up NDK (Android)
        uses: nttld/setup-ndk@v1
        id: ndk
        with:
          ndk-version: r26b

      - name: Configure CMake (Android)
        run: |
          cmake -B build \
            -DCMAKE_TOOLCHAIN_FILE=${{ steps.ndk.outputs.ndk-path }}/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=android-24 \
            -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_path }}
